/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author KoonD
 */
package main.javacode;
import main.javacode.expense.Expense;
import main.javacode.home.home;
import main.javacode.worker.Worker;
import main.javacode.Warehouse.Warehouse;
import java.awt.Cursor;
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        expense = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        worker = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        warehouse = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jButton3.setText("jButton1");

        setBackground(new java.awt.Color(69, 69, 69));
        setPreferredSize(new java.awt.Dimension(200, 720));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 82, Short.MAX_VALUE)
        );

        expense.setBackground(new java.awt.Color(69, 69, 69));
        expense.setForeground(new java.awt.Color(192, 192, 192));
        expense.setToolTipText("");
        expense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expense.setMaximumSize(new java.awt.Dimension(123, 66));
        expense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expenseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expenseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expenseMouseExited(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setText("Expense");

        javax.swing.GroupLayout expenseLayout = new javax.swing.GroupLayout(expense);
        expense.setLayout(expenseLayout);
        expenseLayout.setHorizontalGroup(
                expenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(expenseLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        expenseLayout.setVerticalGroup(
                expenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(expenseLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        worker.setBackground(new java.awt.Color(69, 69, 69));
        worker.setForeground(new java.awt.Color(192, 192, 192));
        worker.setToolTipText("");
        worker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        worker.setPreferredSize(new java.awt.Dimension(123, 66));
        worker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                workerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                workerMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel4.setText("Worker");

        javax.swing.GroupLayout workerLayout = new javax.swing.GroupLayout(worker);
        worker.setLayout(workerLayout);
        workerLayout.setHorizontalGroup(
                workerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(workerLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workerLayout.setVerticalGroup(
                workerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(workerLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        home.setBackground(new java.awt.Color(69, 69, 69));
        home.setForeground(new java.awt.Color(192, 192, 192));
        home.setToolTipText("");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setMaximumSize(new java.awt.Dimension(123, 66));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel6.setText("Home");
        jLabel6.setIconTextGap(10);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
                homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homeLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
                homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homeLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        warehouse.setBackground(new java.awt.Color(69, 69, 69));
        warehouse.setForeground(new java.awt.Color(192, 192, 192));
        warehouse.setToolTipText("");
        warehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        warehouse.setPreferredSize(new java.awt.Dimension(123, 66));
        warehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                warehouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                warehouseMouseEntered(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(192, 192, 192));
        jLabel7.setText("WareHouse");

        javax.swing.GroupLayout warehouseLayout = new javax.swing.GroupLayout(warehouse);
        warehouse.setLayout(warehouseLayout);
        warehouseLayout.setHorizontalGroup(
                warehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(warehouseLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel7)
                                .addContainerGap(71, Short.MAX_VALUE))
        );
        warehouseLayout.setVerticalGroup(
                warehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(warehouseLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel7)
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(worker, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(warehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                                        .addComponent(expense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(worker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(338, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel7.setForeground(new java.awt.Color(192, 192, 192));
        home home1 = new home();
        home.setVisible(true);
// TODO add your handling code here:
    }

    private void expenseMouseClicked(java.awt.event.MouseEvent evt) {
        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel7.setForeground(new java.awt.Color(192, 192, 192));
        Expense expense = new Expense();
        expense.setVisible(true);
        // TODO add your handling code here:
    }

    private void workerMouseClicked(java.awt.event.MouseEvent evt) {
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel7.setForeground(new java.awt.Color(192, 192, 192));
        Worker worker = new Worker();
        worker.setVisible(true);
        // TODO add your handling code here:
    }

    private void warehouseMouseClicked(java.awt.event.MouseEvent evt) {
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        Warehouse wh = new Warehouse();
        wh.setVisible(true);
        // TODO add your handling code here:
    }

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }

    private void expenseMouseEntered(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }

    private void workerMouseEntered(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }

    private void warehouseMouseEntered(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }

    private void homeMouseExited(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getDefaultCursor());
// TODO add your handling code here:
    }

    private void expenseMouseExited(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getDefaultCursor());
// TODO add your handling code here:
    }

    private void workerMouseExited(java.awt.event.MouseEvent evt) {
        setCursor(Cursor.getDefaultCursor());
// TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JPanel expense;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel warehouse;
    private javax.swing.JPanel worker;
    // End of variables declaration
}
